version: '3'

services:
  web:
    build: .
    ports:
      - "${PORT}:3000"
    environment:
      - MONGODB_URI=${MONGO_URI}
      - DATABASE_URL=${POSTGRES_URL}
    depends_on:
      - db
      - postgres

  db:
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:27017"  # 👈 host:container
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  postgres-data:
