version: '3'

services:
  web:
    build: .
    ports:
      - "5001:3000"
    environment:
      - MONGODB_URI=mongodb://db:27019/my_app
      - DATABASE_URL=postgresql://postgres:nour1234@postgres:5432/dashboarddb


    depends_on:
      - db
      - postgres

  db:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - mongo-data:/data/db
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nour1234
      POSTGRES_DB: dashboarddb
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  mongo-data:
  postgres-data:
